language: d
d: dmd

os:
  - linux

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
    packages:
      - llvm-10

#script: sh build.sh
script: dub build
