name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# TODO: Make it run the tests as well
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            install-llvm: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 10
          - os: macos-latest
            install-llvm: brew install llvm

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2

      # Install D and Dub
      - name: D Compiler Installation
        uses: mihails-strasuns/setup-dlang@v1.0.0
        with:
          compiler: dmd-latest

      # Install LLVM 10
      - name: Install LLVM
        run: ${{matrix.install-llvm}}

      # Build dub project
      - name: Build
        run: dub build
        
      # Run dub unittests
      - name: Unittest
        run: dub test
